version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.5.13
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://127.0.0.1:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - thingaround-network
    command:
      - /bin/bash
      - -c
      - |
        (
          echo "Waiting for Kafka to be ready..."
          while ! nc -z localhost 9092; do
            sleep 1
          done
          echo "Kafka is reachable! Creating topics..."
          kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic rental-events --partitions 1 --replication-factor 1
          kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic catalog-events --partitions 1 --replication-factor 1
          kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic catalog-commands --partitions 1 --replication-factor 1
          echo "All topics created successfully!"
        ) &
        exec /etc/confluent/docker/run
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    networks:
      - thingaround-network
  
  db:
    image: postgres:17-alpine
    container_name: database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./Db/persistence:/var/lib/postgresql/data
    networks:
      - thingaround-network
        
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - thingaround-network
    depends_on:
      - db
    
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./Redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./Redis/Data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - thingaround-network

  identity-profile:
    build:
      context: .
      dockerfile: backend_C_sharp/IdentityProfileService/Dockerfile
    container_name: identity_profile_service
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__gRPC__Url=http://*:8080
      - ConnectionStrings__PostgresConnectionString=Host=db;Port=5432;Database=identity_db;Username=admin;Password=admin
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
    volumes:
      - ./backend_C_sharp/IdentityProfileService/Configs:/app/Configs:ro
      - ./backend_C_sharp/Core/Configs:/app/Core/Configs:ro
    networks:
      - thingaround-network
    depends_on:
      - db
      - redis

  gateway:
    build:
      context: .
      dockerfile: backend_C_sharp/Gateway/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - GrpcEndpoints__IdentityProfileService=http://identity-profile:8080
      - GrpcEndpoints__CatalogService=http://catalog:8080
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      - Jwt__Issuer=ThingAround.IdentityServer
      - Jwt__Audience=ThingAround.Client
    volumes:
      - ./backend_C_sharp/Gateway/Configs:/app/Configs:ro
    networks:
      - thingaround-network
    depends_on:
      - identity-profile
      - redis

  catalog:
    build:
      context: .
      dockerfile: backend_C_sharp/CatalogService/Dockerfile
    container_name: catalog_service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__gRPC__Url=http://*:8080
      - ConnectionStrings__PostgresConnectionString=Host=db;Port=5432;Database=catalog_db;Username=admin;Password=admin
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
    networks:
      - thingaround-network
    depends_on:
      - db
      - redis
    
networks:
  thingaround-network:
    driver: bridge