version: '3.8'

services:
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:4.2.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./RabbitMq/Data:/var/lib/rabbitmq
    networks:
      - thingaround-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  db:
    image: postgres:17-alpine
    container_name: database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./Db/persistence:/var/lib/postgresql/data
    networks:
      - thingaround-network
        
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - thingaround-network
    depends_on:
      - db
    
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./Redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./Redis/Data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - thingaround-network

  identity-profile:
    build:
      context: .
      dockerfile: backend_C_sharp/IdentityProfileService/Dockerfile
    container_name: identity_profile_service
    ports:
      - "5000:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__gRPC__Url=http://*:8080
      - ConnectionStrings__PostgresConnectionString=Host=db;Port=5432;Database=identity_db;Username=admin;Password=admin
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
    volumes:
      - ./backend_C_sharp/IdentityProfileService/Configs:/app/Configs:ro
      - ./backend_C_sharp/Core/Configs:/app/Core/Configs:ro
    networks:
      - thingaround-network
    depends_on:
      - db
      - redis

  gateway:
    build:
      context: .
      dockerfile: backend_C_sharp/Gateway/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - GrpcEndpoints__IdentityProfileService=http://identity-profile:8080
      - GrpcEndpoints__CatalogService=http://catalog:8080
      - GrpcEndpoints__RentalService=http://rental:8080
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      - Jwt__Issuer=ThingAround.IdentityServer
      - Jwt__Audience=ThingAround.Client
    volumes:
      - ./backend_C_sharp/Gateway/Configs:/app/Configs:ro
    networks:
      - thingaround-network
    depends_on:
      - identity-profile
      - redis
      - catalog
      - rental

  catalog:
    build:
      context: .
      dockerfile: backend_C_sharp/CatalogService/Dockerfile
    container_name: catalog_service
    ports:
      - "5001:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__gRPC__Url=http://*:8080
    
      - ConnectionStrings__PostgresConnectionString=Host=db;Port=5432;Database=catalog_db;Username=admin;Password=admin
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin
      - RabbitMQ__Exchanges__CatalogEventsExchange=catalog-events
      - RabbitMQ__Exchanges__CatalogCommandsExchange=catalog-commands
      - RabbitMQ__Queues__CatalogServiceQueue=catalog-service
    networks:
      - thingaround-network
    depends_on:
      - db
      - redis
      - rabbitmq
    
  rental:
    build:
      context: .
      dockerfile: backend_C_sharp/RentalService/Dockerfile
    container_name: rental_service
    ports:
      - "5002:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__gRPC__Url=http://*:8080
      
      - ConnectionStrings__PostgresConnectionString=Host=db;Port=5432;Database=rental_db;Username=admin;Password=admin
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      
      - RedisOptions__InstancePrefix=Rental
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin
      - RabbitMQ__Exchanges__RentalEventsExchange=rental-events
      - RabbitMQ__Exchanges__CatalogEventsExchange=catalog-events
      - RabbitMQ__Exchanges__CatalogCommandsExchange=catalog-commands
      - RabbitMQ__Queues__RentalServiceQueue=rental-service
    networks:
      - thingaround-network
    depends_on:
      - db
      - redis
      - rabbitmq
  
networks:
  thingaround-network:
    driver: bridge