bind 0.0.0.0
protected-mode no
port 6379

maxclients 1000

loglevel warning
logfile ""

maxmemory 512mb
maxmemory-policy allkeys-lru

save "" 

save 86400 1

appendonly no

hash-max-ziplist-entries 512
hash-max-ziplist-value 64