spring:
  application:
    name: coownership-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: validate
  liquibase:
    enabled: false
server:
  servlet:
    context-path: /api/v1/co-ownership