<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
      <PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
      <PackageReference Include="OpenIddict.AspNetCore" Version="7.4.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
      <PackageReference Include="Serilog.Enrichers.Span" Version="3.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="BLL\" />
      <Folder Include="Mapper\" />
      <Folder Include="Presentation\" />
      <Folder Include="Protos\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\Core\Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Configs\admins.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.Development.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Properties\launchSettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
