// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260410140258_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<DateTime?>("ReservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_at");

                    b.HasKey("ListingId", "Date")
                        .HasName("pk_availability_slots");

                    b.HasIndex("Date", "IsAvailable")
                        .HasDatabaseName("ix_availability_slots_date_is_available");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Date", "IsAvailable"), new[] { "Price" });

                    b.HasIndex("ListingId", "Date", "IsAvailable")
                        .HasDatabaseName("ix_availability_slots_listing_id_date_is_available");

                    b.ToTable("availability_slots", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.RentalListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_slug");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DefaultPrice")
                        .HasColumnType("integer")
                        .HasColumnName("default_price");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("ImagesUrls")
                        .HasColumnType("text[]")
                        .HasColumnName("images_urls");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<float>("OwnerRating")
                        .HasColumnType("real")
                        .HasColumnName("owner_rating");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('russian', coalesce(\"title\", '') || ' ' || coalesce(\"description\", ''))", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TitleSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_rental_listings");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_rental_listings_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("TitleSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_rental_listings_title_slug");

                    b.HasIndex("City", "CategorySlug", "IsActive", "DefaultPrice")
                        .HasDatabaseName("ix_rental_listings_filters");

                    b.ToTable("rental_listings", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.RentalListing", b =>
                {
                    b.OwnsOne("Domain.Entity.ContactInfo", "Contact", b1 =>
                        {
                            b1.Property<Guid>("RentalListingId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("ManagerId")
                                .HasColumnType("uuid")
                                .HasColumnName("contact_manager_id");

                            b1.Property<string>("PersonName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("contact_person_name");

                            b1.Property<string>("PersonPhone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("contact_person_phone");

                            b1.PrimitiveCollection<List<string>>("SocialsUrls")
                                .HasColumnType("text[]")
                                .HasColumnName("contact_socials_urls");

                            b1.HasKey("RentalListingId");

                            b1.ToTable("rental_listings");

                            b1.WithOwner()
                                .HasForeignKey("RentalListingId")
                                .HasConstraintName("fk_rental_listings_rental_listings_id");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
