spring:
  application:
    name: recommendation-service
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/
  #    username: postgres
  #    password: postgres
  #  jpa:
  #    hibernate:
  #      ddl-auto: validate
server:
  servlet:
    context-path: /api/v1/recommendations